# ✅ General Settings
debug: true

# ✅ Ingestion Settings
signal_input_path: ./examples/EUR_USD_processed_signals.csv
include_columns: "*"
exclude_columns:
  - Date
  - Hour
  - SL_Pips
  - TP1_Pips
  - TP2_Pips
  - SL_Ticks
  - TP1_Ticks
  - TP2_Ticks
  - Stop_Loss_Price
  - Take_Profit_1_Price
  - Take_Profit_2_Price

# ✅ Runtime Settings
deterministic: true
random_seed: 42

# ✅ Static Output Naming (optional override)
output_name: EUR_USD_embeddings.npy

# ✅ Report Settings
report_format: ["matplotlib", "plotly"]
report_palette: Set2
