# config/full_config.yaml

# ✅ General Settings
debug: true

# ✅ Ingestion Settings
signal_input_path: ./examples/EUR_USD_processed_signals.csv
include_columns: "*"
# include_columns:
#   - Open
#   - Close
#   - ATR
#   - AHMA
exclude_columns: ["Date", "Hour"]  # Remove Date/Hour for daily resolution

# ✅ Embedding Settings
output_name: EUR_USD_embeddings.npy
window_size: 15
stride: 1

encoding_method: "sinusoidal"      # Options: 'sinusoidal', 'learnable'
encoding_style: "stacked"      # Options: 'interleaved', 'stacked' (only for sinusoidal)
# embedding_dim: 80                # Required if using encoding_method = 'learnable'

# ✅ Clustering Settings
embedding_path: ./embeddings/EUR_USD_embeddings.npy
regime_data_path: ./data/processed/regime_input.csv
output_dir: ./reports/EUR_USD
n_clusters: 8
