# config/full_config.yaml

# ✅ General Settings
debug: true

# ✅ Ingestion Settings
signal_input_path: ./examples/EUR_USD_processed_signals.csv
include_columns: "*"
# include_columns:
#   - Open
#   - Close
#   - ATR
#   - AHMA
exclude_columns: ["Date", "Hour", "SL_Pips", "TP1_Pips", "TP2_Pips",
  "SL_Ticks", "TP1_Ticks", "TP2_Ticks",
  "Stop_Loss_Price", "Take_Profit_1_Price", "Take_Profit_2_Price"] 

deterministic: true             # ✅ Enables deterministic mode
random_seed: 42                 # ✅ Fixed seed used in all random ops (TF, NumPy, Python)

# ✅ Embedding Settings
output_name: EUR_USD_embeddings.npy
window_size: 3
stride: 1

# Instrument
instrument: EUR_USD

encoding_method: "sinusoidal"      # Options: 'sinusoidal', 'learnable'
encoding_style: "interleaved"      # Options: 'interleaved', 'stacked' (only for sinusoidal)
# embedding_dim: 80                # Required if using encoding_method = 'learnable'

# ✅ Clustering Settings
embedding_path: ./embeddings/EUR_USD_embeddings.npy
regime_data_path: ./data/processed/regime_input.csv
output_dir: ./reports/EUR_USD
n_clusters: 10

report_format: ["matplotlib", "plotly"]  # both
# report_format: ["matplotlib"]          # only static
# report_format: ["plotly"]              # only interactive
# report_format: []      

report_palette: Set2