# configs/ingest_config.yaml

# Enable debug logging (optional)
debug: true

# Path to the input signal-enriched CSV (e.g., includes AHMA, LP, LC, indicators, Movement_Class)
#signal_input_path: data/raw/signal_input.csv
signal_input_path: ./examples/EUR_USD_processed_signals.csv

include_columns: "*"
  # - Open
  # - Close
  # - ATR
  # - AHMA
exclude_columns: ["Date", "Hour", "SL_Pips", "TP1_Pips", "TP2_Pips",
  "SL_Ticks", "TP1_Ticks", "TP2_Ticks",
  "Stop_Loss_Price", "Take_Profit_1_Price", "Take_Profit_2_Price"] 
#   - Predictions
#   - Confidence